"""
ULTRAGENT HUD MANAGER v1.0
==========================
Panel de Control Maestro para observabilidad del sistema.

Implementa:
- Generación dinámica de HUD.md
- Throttling de escrituras (1s mínimo)
- Agregación de estados de todos los módulos
- Human-in-the-loop signals
- Jerarquía visual con <details>
"""

import asyncio
import json
import logging
import os
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from threading import Lock, Thread
from typing import Any, Optional

from neuro_architect import get_neuro_architect

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURACIÓN
# ═══════════════════════════════════════════════════════════════════════════════

PROJECT_ROOT = Path(__file__).parent
AI_DIR = PROJECT_ROOT / os.getenv("AI_CORE_DIR", ".ai")
HUD_FILE = AI_DIR / "HUD.md"
SIGNALS_FILE = AI_DIR / "signals.json"
MEMORY_FILE = AI_DIR / "memory.md"

# Throttling
MIN_REFRESH_INTERVAL = 1.0  # segundos

# Logger
logger = logging.getLogger("ultragent.hud")


# ═══════════════════════════════════════════════════════════════════════════════
# HUD TEMPLATE
# ═══════════════════════════════════════════════════════════════════════════════

HUD_TEMPLATE = """# 🎛️ ULTRAGENT HUD v2.0

> **Last Update:** {timestamp}
> **Mission:** {mission_goal}
> **Uptime:** {uptime}

---

## 🛰️ SYSTEM STATUS

| Component | Status | Details |
|-----------|--------|---------|
| MCP Server | {mcp_status} | v{mcp_version} - {mcp_tools} tools |
| Sentinel | {sentinel_status} | {sentinel_events} events |
| Router | {router_status} | {router_tokens} tokens used |
| Librarian | {librarian_status} | {librarian_docs} docs indexed |
| Scout | {scout_status} | {scout_searches} searches |
| Evolution | {evolution_status} | {evolution_audits} audits |
| Mechanic | {mechanic_status} | Docker: {docker_status} |
| Vision | {vision_status} | {vision_scans} scans |

{human_signal}

---

## ⚡ ACTIVE SWARM

{active_tasks}

---

## 🧬 EVOLUTION SCORE

| Metric | Value |
|--------|-------|
| Latest Fitness | {fitness_score} |
| Grade | {fitness_grade} |
| Iterations | {evolution_iterations} |

{evolution_link}

---

## 👁️ ARCHITECTURE SNAPSHOT

{architecture_image}

---

## 🔔 SENTINEL ALERTS (Last 3)

{sentinel_alerts}

---

<details>
<summary>📊 Detailed Statistics</summary>

### Router Token Usage
{router_details}

### Mechanic Executions
{mechanic_details}

### Scout Repositories
{scout_details}

</details>

---

*Generated by Ultragent HUD Manager v1.0*
"""

HUMAN_SIGNAL_TEMPLATE = """
> [!CAUTION]
> 🛑 **AWAITING HUMAN DECISION**
> 
> **Issue:** {issue}
> **Options:** {options}
"""


# ═══════════════════════════════════════════════════════════════════════════════
# HUD MANAGER
# ═══════════════════════════════════════════════════════════════════════════════

class HUDManager:
    """
    Gestor central de observabilidad.
    
    Recopila datos de todos los módulos y genera el HUD.md
    con throttling para evitar sobrecarga de I/O.
    """
    
    def __init__(self):
        self._lock = Lock()
        self._last_refresh: Optional[datetime] = None
        self._start_time = datetime.now()
        self._mission_goal = "Sistema en espera de misión"
        self._pending_human_signal: Optional[dict] = None
        
        # Asegurar directorio
        AI_DIR.mkdir(parents=True, exist_ok=True)
        
        logger.info("HUDManager inicializado")
    
    def set_mission_goal(self, goal: str) -> None:
        """Define el objetivo global de la misión."""
        with self._lock:
            self._mission_goal = goal
        logger.info(f"Mission goal set: {goal}")
    
    def request_human_decision(
        self,
        issue: str,
        options: list[str],
    ) -> None:
        """Establece una señal de Human-in-the-loop."""
        with self._lock:
            self._pending_human_signal = {
                "issue": issue,
                "options": " | ".join(f"[{o}]" for o in options),
                "timestamp": datetime.now().isoformat(),
            }
        logger.warning(f"Human decision requested: {issue}")
    
    def clear_human_signal(self) -> None:
        """Limpia la señal de decisión humana."""
        with self._lock:
            self._pending_human_signal = None
    
    def _get_uptime(self) -> str:
        """Calcula tiempo de actividad."""
        delta = datetime.now() - self._start_time
        hours, remainder = divmod(int(delta.total_seconds()), 3600)
        minutes, seconds = divmod(remainder, 60)
        return f"{hours:02d}:{minutes:02d}:{seconds:02d}"
    
    def _get_mcp_status(self) -> dict:
        """Obtiene estado del MCP Server."""
        try:
            from mcp_server import mcp
            tools_count = len(mcp._tool_manager._tools)
            return {
                "status": "🟢 Online",
                "version": "2.0",
                "tools": tools_count,
            }
        except Exception as e:
            return {"status": "🔴 Error", "version": "?", "tools": 0}
    
    def _get_sentinel_status(self) -> dict:
        """Obtiene estado del Sentinel."""
        try:
            from sentinel import get_sentinel
            sentinel = get_sentinel()
            status = sentinel.get_status()
            return {
                "status": "🟢 Watching" if status.get("watching") else "🟡 Idle",
                "events": status.get("stats", {}).get("events_detected", 0),
            }
        except Exception:
            return {"status": "⚫ N/A", "events": 0}
    
    def _get_router_status(self) -> dict:
        """Obtiene estado del Router."""
        try:
            from router import get_router
            router = get_router()
            status = router.get_status()
            tokens = status.get("token_usage", {})
            total = sum(
                v.get("total_tokens", 0)
                for v in tokens.values()
                if isinstance(v, dict)
            )
            return {
                "status": "🟢 Ready",
                "tokens": f"{total:,}",
                "details": tokens,
            }
        except Exception:
            return {"status": "⚫ N/A", "tokens": "0", "details": {}}
    
    def _get_librarian_status(self) -> dict:
        """Obtiene estado del Librarian."""
        try:
            from librarian import get_librarian
            librarian = get_librarian()
            status = librarian.get_status()
            return {
                "status": "🟢 Ready",
                "docs": status.get("documents_indexed", 0),
            }
        except Exception:
            return {"status": "⚫ N/A", "docs": 0}
    
    def _get_scout_status(self) -> dict:
        """Obtiene estado del Scout."""
        try:
            from scout import get_scout
            scout = get_scout()
            status = scout.get_status()
            stats = status.get("stats", {})
            return {
                "status": "🟢 Ready" if status.get("has_token") else "🟡 No Token",
                "searches": stats.get("searches", 0),
                "details": stats,
            }
        except Exception:
            return {"status": "⚫ N/A", "searches": 0, "details": {}}
    
    def _get_evolution_status(self) -> dict:
        """Obtiene estado del Evolution."""
        try:
            from evolution import get_evolution
            evolution = get_evolution()
            status = evolution.get_status()
            stats = status.get("stats", {})
            latest = evolution.get_latest_fitness()
            return {
                "status": "🟢 Ready",
                "audits": stats.get("audits_performed", 0),
                "fitness": f"{latest:.1f}" if latest else "N/A",
                "grade": "N/A",
                "iterations": status.get("current_iteration", 0),
            }
        except Exception:
            return {
                "status": "⚫ N/A",
                "audits": 0,
                "fitness": "N/A",
                "grade": "N/A",
                "iterations": 0,
            }
    
    def _get_mechanic_status(self) -> dict:
        """Obtiene estado del Mechanic."""
        try:
            from mechanic import get_mechanic
            mechanic = get_mechanic()
            status = mechanic.get_status()
            stats = status.get("stats", {})
            return {
                "status": "🟢 Ready" if status.get("docker_available") else "🟡 No Docker",
                "docker": "Available" if status.get("docker_available") else "Offline",
                "details": stats,
            }
        except Exception:
            return {"status": "⚫ N/A", "docker": "Unknown", "details": {}}
    
    def _get_vision_status(self) -> dict:
        """Obtiene estado del Vision."""
        try:
            from vision import get_vision
            vision = get_vision()
            status = vision.get_status()
            stats = status.get("stats", {})
            return {
                "status": "🟢 Ready",
                "scans": stats.get("scans", 0),
            }
        except Exception:
            return {"status": "⚫ N/A", "scans": 0}
    
    def _get_sentinel_alerts(self) -> str:
        """Obtiene últimas alertas del Sentinel."""
        try:
            if SIGNALS_FILE.exists():
                data = json.loads(SIGNALS_FILE.read_text(encoding="utf-8"))
                events = data.get("events", [])[-3:]
                if events:
                    lines = []
                    for e in reversed(events):
                        ts = e.get("timestamp", "")[:19]
                        path = Path(e.get("path", "")).name
                        etype = e.get("event_type", "unknown")
                        lines.append(f"- `{ts}` | **{etype}** | `{path}`")
                    return "\n".join(lines)
            return "- No alerts detected"
        except Exception:
            return "- Unable to read alerts"
    
    def _get_architecture_image(self) -> str:
        """Obtiene referencia a la última imagen de arquitectura."""
        try:
            reports_dir = AI_DIR / "reports"
            if reports_dir.exists():
                pngs = sorted(reports_dir.glob("architecture_map_*.png"))
                if pngs:
                    latest = pngs[-1]
                    return f"![Architecture]({latest})"
            return "*No architecture graph generated yet. Run `visualize_architecture`.*"
        except Exception:
            return "*Unable to load architecture graph.*"
    
    def _format_details(self, data: dict, title: str = "") -> str:
        """Formatea un diccionario como tabla markdown."""
        if not data:
            return "No data available"
        
        lines = [f"| Key | Value |", "| --- | --- |"]
        for k, v in data.items():
            lines.append(f"| {k} | {v} |")
        return "\n".join(lines)
    
    def refresh_dashboard(self, force: bool = False) -> str:
        """
        Regenera el HUD.md con datos actuales.
        
        Args:
            force: Ignorar throttling
            
        Returns:
            Contenido del HUD generado
        """
        with self._lock:
            # Throttling
            if not force and self._last_refresh:
                elapsed = (datetime.now() - self._last_refresh).total_seconds()
                if elapsed < MIN_REFRESH_INTERVAL:
                    return HUD_FILE.read_text(encoding="utf-8") if HUD_FILE.exists() else ""
            
            self._last_refresh = datetime.now()
        
        # Recopilar estados
        mcp = self._get_mcp_status()
        sentinel = self._get_sentinel_status()
        router = self._get_router_status()
        librarian = self._get_librarian_status()
        scout = self._get_scout_status()
        evolution = self._get_evolution_status()
        mechanic = self._get_mechanic_status()
        vision = self._get_vision_status()
        
        # Feed NeuroArchitect (Hyper-V)
        self._feed_neuro_architect(mcp, sentinel, router, evolution)
        
        # Human signal
        human_signal = ""
        if self._pending_human_signal:
            human_signal = HUMAN_SIGNAL_TEMPLATE.format(**self._pending_human_signal)
        
        # Evolution link (placeholder)
        evolution_link = ""
        reports_dir = AI_DIR / "reports"
        if reports_dir.exists():
            audits = sorted(reports_dir.glob("audit_*.json"))
            if audits:
                evolution_link = f"[View Latest Report]({audits[-1]})"
        
        # Generar contenido
        content = HUD_TEMPLATE.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            mission_goal=self._mission_goal,
            uptime=self._get_uptime(),
            mcp_status=mcp["status"],
            mcp_version=mcp["version"],
            mcp_tools=mcp["tools"],
            sentinel_status=sentinel["status"],
            sentinel_events=sentinel["events"],
            router_status=router["status"],
            router_tokens=router["tokens"],
            librarian_status=librarian["status"],
            librarian_docs=librarian["docs"],
            scout_status=scout["status"],
            scout_searches=scout["searches"],
            evolution_status=evolution["status"],
            evolution_audits=evolution["audits"],
            mechanic_status=mechanic["status"],
            docker_status=mechanic["docker"],
            vision_status=vision["status"],
            vision_scans=vision["scans"],
            human_signal=human_signal,
            active_tasks="*No active tasks. System idle.*",
            fitness_score=evolution["fitness"],
            fitness_grade=evolution["grade"],
            evolution_iterations=evolution["iterations"],
            evolution_link=evolution_link,
            architecture_image=self._get_architecture_image(),
            sentinel_alerts=self._get_sentinel_alerts(),
            router_details=self._format_details(router.get("details", {})),
            mechanic_details=self._format_details(mechanic.get("details", {})),
            scout_details=self._format_details(scout.get("details", {})),
        )
        
        # Escribir archivo
        HUD_FILE.write_text(content, encoding="utf-8")
        
        logger.debug("HUD refreshed")
        
        return content
    
    def _feed_neuro_architect(self, mcp, sentinel, router, evolution):
        """Alimenta el sistema nervioso con datos frescos."""
        try:
            neuro = get_neuro_architect()
            
            # Router Stats -> Neuro
            if "details" in router:
                for model, stats in router["details"].items():
                     neuro.ingest_telemetry(
                         "router", 
                         "execution", 
                         {"model": model, "stats": stats}
                     )
                     
            # Evolution -> Neuro
            neuro.ingest_telemetry(
                "evolution",
                "variable_update",
                {"fitness": evolution.get("fitness", 0)}
            )
            
            # Exportar mapa para visualización
            neuro.export_neuro_map()
            
        except Exception as e:
            logger.warning(f"Failed to feed neuro architect: {e}")
    
    def get_full_status(self) -> dict:
        """Retorna resumen del estado completo del sistema."""
        content = self.refresh_dashboard(force=True)
        return {
            "hud_path": str(HUD_FILE),
            "content": content,
            "mission": self._mission_goal,
            "uptime": self._get_uptime(),
            "has_human_signal": self._pending_human_signal is not None,
        }
    
    def export_session(self, output_path: Optional[str] = None) -> str:
        """
        Exporta la sesión completa como zip.
        
        Returns:
            Path al archivo zip generado
        """
        import shutil
        
        if output_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = str(PROJECT_ROOT / f"ultragent_session_{timestamp}.zip")
        
        # Crear zip de .ai/
        shutil.make_archive(
            output_path.replace(".zip", ""),
            "zip",
            str(AI_DIR),
        )
        
        logger.info(f"Session exported: {output_path}")
        
        return output_path


# ═══════════════════════════════════════════════════════════════════════════════
# SINGLETON
# ═══════════════════════════════════════════════════════════════════════════════

_hud_instance: Optional[HUDManager] = None
_hud_lock = Lock()


def get_hud_manager() -> HUDManager:
    """Obtiene la instancia singleton del HUD Manager."""
    global _hud_instance
    with _hud_lock:
        if _hud_instance is None:
            _hud_instance = HUDManager()
        return _hud_instance


# ═══════════════════════════════════════════════════════════════════════════════
# CLI PARA TESTING
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%H:%M:%S",
    )
    
    print("=" * 60)
    print("ULTRAGENT HUD MANAGER v1.0 - Test")
    print("=" * 60)
    
    hud = get_hud_manager()
    hud.set_mission_goal("Test mission - System verification")
    
    print("\nGenerando HUD...")
    content = hud.refresh_dashboard(force=True)
    
    print(f"\nHUD generado: {HUD_FILE}")
    print(f"Contenido: {len(content)} caracteres")
    print("\n" + "=" * 60)
    print(content[:1000] + "...")
